name: kaitabi_bot

on:
  schedule:
    # Schedule for UTC
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.9 environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
        run: |
          poetry install

      - name: Run script
        id: crawl
        run: |
          python kaitabi_crawler/crawl.py | tee ./result.jsonl
          python print_discord.py > ./result.txt
          value=$(cat ./result.txt)
          value="${value//'%'/'%25'}"
          value="${value//$'\n'/'%0A'}"
          value="${value//$'\r'/'%0D'}"
          echo "::set-output name=result::${value}"

      
      - name: Post to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 予約可能状況
          description: |
            ${{ steps.crawl.outputs.result }}
          nodetail: true
