# This is a basic workflow to help you get started with Actions

name: kaitabi_bot

on:
  schedule:
    # Schedule for UTC
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        id: crawl
        run: |
          python kaitabi_crawler/crawl.py
      
      - name: Post to Discord
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ steps.crawl.outputs.result }}
