# This is a basic workflow to help you get started with Actions

name: kaitabi_bot

on:
  schedule:
    # Schedule for UTC
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install scrapy==2.6.3

      - name: Run script
        run: |
          python kaitabi_crawler/crawl.py
